:stem:

= Practice 3-1
Author: Adam Disney <adisney1@utk.edu>
:toc:

== Problems

=== Problem 1
Show, by means of a counterexample, that the following "greedy" strategy does
not always determine an optimal way to cut rods. Define the *_density_* of a
rod of length _i_ to be stem:[p_i // i], that is, its value per inch. The greedy
strategy for a rod of length _n_ cuts off a first piece of length _i_, where
stem:[1 <= i <= n], having maximum density. It then continues by applying the
greedy strategy to the remaining piece of length stem:[n - 1].


== Answers


=== Answer 1
Take the example from the book on figures 14.1 and 14.2. We have a rod of length
4 and a price table as follows

[%noheader, width=50%]
|===
| length stem:[i]  | 1 | 2 | 3 | 4
| price stem:[p_i] | 1 | 5 | 8 | 9
|===

The greedy algorithm described would look at all possible cuts and evaluate the
density of the cut. Here is a list of the density values for each cut.

. stem:[1 // 1 = 1]
. stem:[5 // 2 = 2.5]
. stem:[8 // 3 ~~ 2.66]
. stem:[9 // 4 = 2.25]

Thus, the algorithm would choose to make a cut of 3 leaving the remaining rod
at length 1 which is a value of 1. This is a total of 9 value, but if we cut it
into two pieces of length 2, the total value would be 10. Thus, the greedy
algorithm doesn't always determine an optimal way to cut rods.
